### ISSUE TITLE
Create a welcome page for our portal.

### ISSUE THREAD

**Issue by rahuldecoded** [rahuldecoded/Gourrier#1]
It should contain a Title(Gourrier), Login portal, contact us, option for Package tracking and checking the Pincode for delivery.

**Comment by saanjh** [comment]
it should contain the following sections:
1.HOME 2.ABOUT US 3.COURIER 4.REGISTER 5.LOGIN 6.CONTACT US
7.TRACK YOUR CONSIGNMENT
8.International courier servies
9.Rate Calculator
10. Pick Up Request
11.Restricted Items
12.Pincode Served
12.Customers Reviews
13.Complaint Box

**Comment by rahuldecoded** [comment]
@saanjh Which things to be added on header?

**Comment by rahuldecoded** [comment]
@manishkumar220296: 1 to 7 are to be added in header.

**Comment by rahuldecoded** [comment]
Done.
